#! /bin/bash

use_color=true
eval $(dircolors -b ~/.dotfiles/env/dircolors)

export CLICOLOR=1
export LSCOLORS=gxfxcxdxbxegedabagacad
export GREP_COLOR='3;33'

man() {
    env LESS_TERMCAP_mb=$'\E[01;31m' \
    LESS_TERMCAP_md=$'\E[01;38;5;74m' \
    LESS_TERMCAP_me=$'\E[0m' \
    LESS_TERMCAP_se=$'\E[0m' \
    LESS_TERMCAP_so=$'\E[38;5;246m' \
    LESS_TERMCAP_ue=$'\E[0m' \
    LESS_TERMCAP_us=$'\E[04;38;5;146m' \
    man "$@"
}
