#! /bin/bash

export LANG='en_US.UTF-8'
export TERM='rxvt-unicode-256color'
export LC_ALL='en_US.UTF-8'
export HISTCONTROL='ignoredups:ignorespace:erasedups'
export HISTSIZE='10000'
export HISTFILESIZE='2000'
export BROWSER='chromium'

# Pager
[[ -x $(which less) ]] && export PAGER=less || export PAGER=more
export LESS="-iRMq"
man --no-justification -w man &>/dev/null && export MANOPT="--no-justification"

# Editer
# Use vim if available even if I type 'vi'
if [[ -x $(which vim) ]] ; then
  export EDITOR=vim ; export VISUAL=vim ; alias vi=vim
else
  export EDITOR=vi ; export VISUAL=vi
fi

export VIMINIT='let $MYVIMRC="/home/$USER/.dotfiles/vim/vimrc" | source $MYVIMRC'
