#! /bin/bash

if [ -d ~/bin ] ; then
  PATH=~/bin:"${PATH}"                           # Local user scripts which are found in /home/$USER/bin
fi

# PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH" # Local user ruby gems
# [[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm"
# PATH=$PATH:$HOME/.rvm/bin                           # Add RVM to PATH for scripting
